import Vue from 'vue'
import { Button, Form, FormItem, Input, Message, Container, Header, Aside, Main, menu, Submenu, MenuItemGroup, MenuItem, Row, Col, Breadcrumb, BreadcrumbItem
        ,Card, Dialog, Table, TableColumn, Switch, Tooltip, Pagination, Tag, MessageBox} from 'element-ui'

Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(menu)
Vue.use(Submenu)
Vue.use(MenuItemGroup)
Vue.use(MenuItem)
Vue.use(Row)
Vue.use(Col)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(Dialog)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Switch)
Vue.use(Tooltip)
Vue.use(Pagination)
Vue.use(Tag)
Vue.use(MessageBox)
Vue.use(Message)
Vue.prototype.$message = Message
